//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.16 at 05:04:22 PM MST 
//


package edu.asu.lerna.iolaus.domain.queryobject;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClausePropertyList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClausePropertyList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="propertyList" type="{http://www.example.org/Iolaus}ClauseProperty"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClausePropertyList", propOrder = {
    "propertyList"
})
public class ClausePropertyList {

    @XmlElement(required = true)
    protected ClauseProperty propertyList;

    /**
     * Gets the value of the propertyList property.
     * 
     * @return
     *     possible object is
     *     {@link ClauseProperty }
     *     
     */
    public ClauseProperty getPropertyList() {
        return propertyList;
    }

    /**
     * Sets the value of the propertyList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClauseProperty }
     *     
     */
    public void setPropertyList(ClauseProperty value) {
        this.propertyList = value;
    }

}
