//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.16 at 05:04:22 PM MST 
//


package edu.asu.lerna.iolaus.domain.queryobject;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.example.iolaus package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _QueryType_QNAME = new QName("http://www.example.org/Iolaus", "QueryType");
    private final static QName _Query_QNAME = new QName("http://www.example.org/Iolaus", "Query");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.example.iolaus
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link QueryType }
     * 
     */
    public QueryType createQueryType() {
        return new QueryType();
    }

    /**
     * Create an instance of {@link DataBaseType }
     * 
     */
    public DataBaseType createDataBaseType() {
        return new DataBaseType();
    }

    /**
     * Create an instance of {@link SelectType }
     * 
     */
    public SelectType createSelectType() {
        return new SelectType();
    }

    /**
     * Create an instance of {@link ClausePropertyList }
     * 
     */
    public ClausePropertyList createClausePropertyList() {
        return new ClausePropertyList();
    }

    /**
     * Create an instance of {@link ClauseProperty }
     * 
     */
    public ClauseProperty createClauseProperty() {
        return new ClauseProperty();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link SelectPropertyType }
     * 
     */
    public SelectPropertyType createSelectPropertyType() {
        return new SelectPropertyType();
    }

    /**
     * Create an instance of {@link DataSetType }
     * 
     */
    public DataSetType createDataSetType() {
        return new DataSetType();
    }

    /**
     * Create an instance of {@link ClauseType }
     * 
     */
    public ClauseType createClauseType() {
        return new ClauseType();
    }

    /**
     * Create an instance of {@link WhereType }
     * 
     */
    public WhereType createWhereType() {
        return new WhereType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Iolaus", name = "QueryType")
    public JAXBElement<QueryType> createQueryType(QueryType value) {
        return new JAXBElement<QueryType>(_QueryType_QNAME, QueryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Iolaus", name = "Query")
    public JAXBElement<QueryType> createQuery(QueryType value) {
        return new JAXBElement<QueryType>(_Query_QNAME, QueryType.class, null, value);
    }

}
