//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.15 at 05:10:27 PM MST 
//


package edu.asu.lerna.iolaus.domain.plainqueryobject.impl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cypher complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cypher">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://digitalhps.org/lerna-plainquery-model}cypher"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cypher", propOrder = {
    "cypher"
})
public class Cypher {

    @XmlElement(required = true)
    protected String cypher;

    /**
     * Gets the value of the cypher property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCypher() {
        return cypher;
    }

    /**
     * Sets the value of the cypher property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCypher(String value) {
        this.cypher = value;
    }

}
