//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.15 at 05:10:27 PM MST 
//


package edu.asu.lerna.iolaus.domain.plainqueryobject.impl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.digitalhps.lerna_plainquery_model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Cypher_QNAME = new QName("http://digitalhps.org/lerna-plainquery-model", "cypher");
    private final static QName _Query_QNAME = new QName("http://digitalhps.org/lerna-plainquery-model", "query");
    private final static QName _Database_QNAME = new QName("http://digitalhps.org/lerna-plainquery-model", "database");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.digitalhps.lerna_plainquery_model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Cypher }
     * 
     */
    public Cypher createCypher() {
        return new Cypher();
    }

    /**
     * Create an instance of {@link Query }
     * 
     */
    public Query createQuery() {
        return new Query();
    }

    /**
     * Create an instance of {@link DatabaseList }
     * 
     */
    public DatabaseList createDatabaseList() {
        return new DatabaseList();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/lerna-plainquery-model", name = "cypher")
    public JAXBElement<String> createCypher(String value) {
        return new JAXBElement<String>(_Cypher_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/lerna-plainquery-model", name = "query")
    public JAXBElement<String> createQuery(String value) {
        return new JAXBElement<String>(_Query_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://digitalhps.org/lerna-plainquery-model", name = "database")
    public JAXBElement<String> createDatabase(String value) {
        return new JAXBElement<String>(_Database_QNAME, String.class, null, value);
    }

}
