//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.16 at 05:04:22 PM MST 
//


package edu.asu.lerna.iolaus.domain.queryobject;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QueryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QueryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Select" type="{http://www.example.org/Iolaus}SelectType"/>
 *         &lt;element name="Where" type="{http://www.example.org/Iolaus}WhereType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Database" type="{http://www.example.org/Iolaus}DataBaseType"/>
 *         &lt;element name="DataSet" type="{http://www.example.org/Iolaus}DataSetType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QueryType", propOrder = {
    "select",
    "where",
    "database",
    "dataSet"
})
public class QueryType {

    @XmlElement(name = "Select", required = true)
    protected SelectType select;
    @XmlElement(name = "Where")
    protected List<WhereType> where;
    @XmlElement(name = "Database", required = true)
    protected DataBaseType database;
    @XmlElement(name = "DataSet", required = true)
    protected DataSetType dataSet;

    /**
     * Gets the value of the select property.
     * 
     * @return
     *     possible object is
     *     {@link SelectType }
     *     
     */
    public SelectType getSelect() {
        return select;
    }

    /**
     * Sets the value of the select property.
     * 
     * @param value
     *     allowed object is
     *     {@link SelectType }
     *     
     */
    public void setSelect(SelectType value) {
        this.select = value;
    }

    /**
     * Gets the value of the where property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the where property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWhere().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WhereType }
     * 
     * 
     */
    public List<WhereType> getWhere() {
        if (where == null) {
            where = new ArrayList<WhereType>();
        }
        return this.where;
    }

    /**
     * Gets the value of the database property.
     * 
     * @return
     *     possible object is
     *     {@link DataBaseType }
     *     
     */
    public DataBaseType getDatabase() {
        return database;
    }

    /**
     * Sets the value of the database property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataBaseType }
     *     
     */
    public void setDatabase(DataBaseType value) {
        this.database = value;
    }

    /**
     * Gets the value of the dataSet property.
     * 
     * @return
     *     possible object is
     *     {@link DataSetType }
     *     
     */
    public DataSetType getDataSet() {
        return dataSet;
    }

    /**
     * Sets the value of the dataSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSetType }
     *     
     */
    public void setDataSet(DataSetType value) {
        this.dataSet = value;
    }

}
