//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.13 at 05:02:37 PM MST 
//


package edu.asu.lerna.iolaus.domain.plainqueryobject.impl;

import javax.xml.bind.annotation.XmlRegistry;

import edu.asu.lerna.iolaus.domain.plainqueryobject.IDatabase;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.digitalhps.plain_query package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.digitalhps.plain_query
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DatabaseList }
     * 
     */
    public DatabaseList createDatabaseList() {
        return new DatabaseList();
    }

    /**
     * Create an instance of {@link Query }
     * 
     */
    public Query createQuery() {
        return new Query();
    }

    /**
     * Create an instance of {@link Database}
     * 
     */
    public IDatabase createDatabaseListDatabase() {
        return new Database();
    }

}
