//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.13 at 05:02:37 PM MST 
//

package edu.asu.lerna.iolaus.domain.plainqueryobject.impl;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlAdapter;

import edu.asu.lerna.iolaus.domain.plainqueryobject.IQuery;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="databaseList" type="{http://digitalhps.org/plain_query}databaseList"/>
 *         &lt;element name="cypher" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "databaseList", "cypher" })
@XmlRootElement(name = "query")
public class Query implements IQuery {

	@XmlElement(required = true)
	protected List<String> databaseList;
	@XmlElement(required = true)
	protected String cypher;

	/* (non-Javadoc)
	 * @see edu.asu.lerna.iolaus.domain.queryobject.impl.IQuery#getDatabase()
	 */
    @Override
	public List<String> getDatabaseList() {
        return databaseList;
    }

    /* (non-Javadoc)
	 * @see edu.asu.lerna.iolaus.domain.queryobject.impl.IQuery#setDatabase(edu.asu.lerna.iolaus.domain.queryobject.IDatabase)
	 */
    @Override
	public void setDatabaseList(List<String> value) {
        this.databaseList = value;
    }
    
	/**
	 * Gets the value of the cypher property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCypher() {
		return cypher;
	}

	/**
	 * Sets the value of the cypher property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCypher(String value) {
		this.cypher = value;
	}

	public static class Adapter extends XmlAdapter<Query, IQuery> {
		public IQuery unmarshal(Query v) {
			return v;
		}

		public Query marshal(IQuery v) {
			return (Query) v;
		}

	}

}
